sudo: required

language: ruby

services:
  - docker

cache: apt

before_install:
  - make setup

before_script:
  - cd $TRAVIS_BUILD_DIR
  - make info

script: make run

after_success: make check

notifications:
  email: false
